FROM bnbalsamo/flask_stack

ARG MVOL_API_MVOL_ROOT
ARG MVOL_API_RETRIEVER_URL
ARG MVOL_API_VERBOSITY=WARN

ENV MVOL_API_MVOL_ROOT=$MVOL_API_MVOL_ROOT \
    MVOL_API_RETRIEVER_URL=$MVOL_API_RETRIEVER_URL \
    MVOL_API_VERBOSITY=$MVOL_API_VERBOSITY \
    APP_NAME=mvol_api

RUN ["test", "-n", "$MVOL_API_MVOL_ROOT"]
RUN ["test", "-n", "$MVOL_API_RETRIEVER_URL"]
